import { Recipe } from './types';

export const ALL_RECIPES: Recipe[] = [
  // ─── POLLO (10) ───────────────────────────────────────────────────────────
  {
    id: 'r_pollo_01',
    title: 'Pollo Asado con Papas',
    description: 'Pollo entero sazonado con achiote, ajo y comino, asado al horno hasta dorar. Acompañado de papas criollas.',
    prepTime: 45,
    energyLevel: 'balanced',
    utensils: ['horno', 'bandeja para horno', 'cuchillo', 'tazón'],
    ingredientsNeeded: [
      { name: 'pollo entero o presas', required: true, inPantry: false },
      { name: 'papas criollas', required: true, inPantry: false },
      { name: 'achiote en polvo', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'comino molido', required: true, inPantry: false },
      { name: 'aceite vegetal', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Precalienta el horno a 200 °C. Lava y seca el pollo con papel absorbente.',
      'Mezcla el aceite, achiote, ajo picado, comino, sal y pimienta para hacer un adobo.',
      'Unta el adobo por todo el pollo, por dentro y por fuera.',
      'Coloca las papas criollas lavadas alrededor del pollo en la bandeja.',
      'Hornea 40–45 minutos, bañando el pollo con sus jugos a mitad de cocción.',
      'Deja reposar 5 minutos antes de servir.',
    ],
    imageUrl: '/images/recipes/r_pollo_01.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_02',
    title: 'Arroz con Pollo Colombiano',
    description: 'Arroz amarillo cocinado con presas de pollo, hogao y verduras. Un clásico de los almuerzos familiares.',
    prepTime: 40,
    energyLevel: 'balanced',
    utensils: ['olla grande', 'sartén', 'cuchara de madera'],
    ingredientsNeeded: [
      { name: 'presas de pollo', required: true, inPantry: false },
      { name: 'arroz', required: true, inPantry: false },
      { name: 'tomate', required: true, inPantry: false },
      { name: 'cebolla cabezona', required: true, inPantry: false },
      { name: 'pimentón rojo', required: false, inPantry: false },
      { name: 'achiote', required: true, inPantry: false },
      { name: 'caldo de pollo', required: true, inPantry: false },
      { name: 'cilantro', required: false, inPantry: false },
    ],
    steps: [
      'Sofríe la cebolla, tomate y pimentón picados en aceite hasta pochar. Reserva el hogao.',
      'Dora las presas de pollo salpimentadas en la misma olla.',
      'Agrega el hogao al pollo, el achiote y revuelve bien.',
      'Incorpora el arroz lavado y el caldo caliente en proporción 1:2.',
      'Cocina a fuego alto hasta que el caldo se absorba, luego baja el fuego, tapa y deja 15 min.',
      'Esponja con un tenedor, esparce cilantro y sirve caliente.',
    ],
    imageUrl: '/images/recipes/r_pollo_02.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_03',
    title: 'Pollo Guisado con Hogao',
    description: 'Presas de pollo estofadas en salsa de tomate y cebolla, el hogao que define la cocina colombiana.',
    prepTime: 35,
    energyLevel: 'balanced',
    utensils: ['olla', 'sartén', 'cuchara de madera'],
    ingredientsNeeded: [
      { name: 'presas de pollo', required: true, inPantry: false },
      { name: 'tomate chonto', required: true, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'comino', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
    ],
    steps: [
      'Salpimienta el pollo y dóralo en aceite caliente por todos lados. Retira y reserva.',
      'En la misma olla sofríe la cebolla larga y el ajo hasta transparentar.',
      'Agrega el tomate picado y el comino. Cocina 8 minutos hasta hacer el hogao.',
      'Regresa el pollo a la olla, cubre con un poco de agua o caldo.',
      'Tapa y cocina a fuego medio 20 minutos hasta que el pollo esté tierno.',
      'Sirve con arroz blanco y patacones.',
    ],
    imageUrl: '/images/recipes/r_pollo_03.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_04',
    title: 'Pollo al Ajillo Criollo',
    description: 'Pechuga de pollo salteada con abundante ajo, cilantro y especias criollas. Rápido y lleno de sabor.',
    prepTime: 20,
    energyLevel: 'low',
    utensils: ['sartén', 'cuchillo', 'tabla de cortar'],
    ingredientsNeeded: [
      { name: 'pechuga de pollo', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'cilantro fresco', required: true, inPantry: false },
      { name: 'aceite de oliva', required: true, inPantry: false },
      { name: 'limón', required: true, inPantry: false },
      { name: 'comino', required: false, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Corta la pechuga en tiras delgadas y salpimienta con comino.',
      'Calienta el aceite en la sartén a fuego alto y agrega el ajo laminado.',
      'Saltea el pollo 4–5 minutos por lado hasta dorar completamente.',
      'Exprime el limón sobre el pollo y agrega el cilantro picado.',
      'Revuelve y sirve de inmediato con arroz o ensalada.',
    ],
    imageUrl: '/images/recipes/r_pollo_04.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_05',
    title: 'Pollo Frito Crujiente',
    description: 'Presas de pollo marinadas en suero costeño y especias, fritas hasta lograr una costra dorada y crujiente.',
    prepTime: 30,
    energyLevel: 'disconnect',
    utensils: ['olla profunda', 'tazón', 'pinzas', 'papel absorbente'],
    ingredientsNeeded: [
      { name: 'presas de pollo', required: true, inPantry: false },
      { name: 'suero costeño o buttermilk', required: true, inPantry: false },
      { name: 'harina de trigo', required: true, inPantry: false },
      { name: 'ajo en polvo', required: true, inPantry: false },
      { name: 'paprika', required: false, inPantry: false },
      { name: 'aceite para freír', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Marina el pollo en suero costeño con sal, ajo en polvo y pimienta mínimo 15 minutos.',
      'Mezcla la harina con paprika, ajo en polvo y sal en un tazón.',
      'Escurre el pollo y pásalo por la harina sazonada, presionando bien.',
      'Calienta el aceite a 175 °C en la olla profunda.',
      'Fríe el pollo en tandas 12–15 minutos hasta dorar. Escurre en papel absorbente.',
      'Sirve con papas fritas y ají casero.',
    ],
    imageUrl: '/images/recipes/r_pollo_05.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_06',
    title: 'Pechuga a la Plancha con Limón',
    description: 'Pechuga de pollo marinada en limón y hierbas, cocinada a la plancha. Opción ligera y proteica.',
    prepTime: 15,
    energyLevel: 'low',
    utensils: ['sartén o plancha', 'tazón', 'cuchillo'],
    ingredientsNeeded: [
      { name: 'pechuga de pollo', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'orégano', required: false, inPantry: false },
      { name: 'aceite de oliva', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Aplancha la pechuga con un mazo para que tenga grosor uniforme.',
      'Marina en limón, ajo picado, orégano, aceite, sal y pimienta por 10 minutos.',
      'Calienta la plancha o sartén a fuego alto con un poco de aceite.',
      'Cocina la pechuga 4–5 minutos por lado sin moverla para lograr marcas.',
      'Deja reposar 2 minutos antes de cortar y sirve con ensalada o arroz.',
    ],
    imageUrl: '/images/recipes/r_pollo_06.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_07',
    title: 'Sopa de Pollo con Verduras',
    description: 'Caldo reconfortante de pollo con papa, zanahoria y cilantro, ideal para días fríos en el altiplano.',
    prepTime: 40,
    energyLevel: 'disconnect',
    utensils: ['olla grande', 'cuchillo', 'tabla de cortar'],
    ingredientsNeeded: [
      { name: 'pollo en presas', required: true, inPantry: false },
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'zanahoria', required: true, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'cilantro', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'sal y comino', required: true, inPantry: false },
    ],
    steps: [
      'Hierve el pollo con agua, cebolla, ajo, sal y comino por 20 minutos.',
      'Retira el pollo, deja enfriar y desmecha la carne. Reserva el caldo.',
      'Pela y pica las papas y zanahorias en cubos medianos.',
      'Regresa el caldo al fuego, agrega las papas y zanahorias. Cocina 15 minutos.',
      'Incorpora el pollo desmechado al caldo y ajusta la sal.',
      'Sirve caliente con cilantro picado y arepa.',
    ],
    imageUrl: '/images/recipes/r_pollo_07.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_08',
    title: 'Pasta con Pollo y Hogao',
    description: 'Pasta corta mezclada con pollo desmenuzado y la icónica salsa hogao colombiana de tomate y cebolla.',
    prepTime: 30,
    energyLevel: 'balanced',
    utensils: ['olla', 'sartén', 'colador', 'cuchara'],
    ingredientsNeeded: [
      { name: 'pasta penne o fusilli', required: true, inPantry: false },
      { name: 'pechuga de pollo cocida', required: true, inPantry: false },
      { name: 'tomate chonto', required: true, inPantry: false },
      { name: 'cebolla cabezona', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
      { name: 'sal, comino y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Cocina la pasta en agua con sal según las instrucciones del empaque. Escurre.',
      'Sofríe la cebolla y el ajo en aceite hasta dorar.',
      'Agrega el tomate picado y el comino. Cocina 8 minutos hasta reducir (hogao).',
      'Desmecha el pollo cocido y añádelo al hogao. Mezcla bien.',
      'Incorpora la pasta escurrida, revuelve y ajusta la sal.',
      'Sirve caliente con queso costeño rallado encima.',
    ],
    imageUrl: '/images/recipes/r_pollo_08.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_09',
    title: 'Pollo Encebollado',
    description: 'Presas de pollo braseadas con mucha cebolla caramelizada y especias. Sabor profundo con arroz blanco.',
    prepTime: 35,
    energyLevel: 'balanced',
    utensils: ['sartén profunda', 'cuchara de madera', 'tapa'],
    ingredientsNeeded: [
      { name: 'presas de pollo', required: true, inPantry: false },
      { name: 'cebolla cabezona', required: true, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'salsa de tomate', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
      { name: 'sal, pimienta y laurel', required: true, inPantry: false },
    ],
    steps: [
      'Dora el pollo salpimentado en aceite caliente por ambos lados. Retira.',
      'En la misma sartén sofríe las cebollas laminadas a fuego medio 10 minutos hasta dorar.',
      'Agrega el ajo y la salsa de tomate. Revuelve y cocina 3 minutos.',
      'Regresa el pollo, agrega la hoja de laurel y un chorrito de agua.',
      'Tapa y cocina a fuego bajo 20 minutos hasta que el pollo esté tierno.',
      'Rectifica la sazón y sirve con arroz blanco.',
    ],
    imageUrl: '/images/recipes/r_pollo_09.jpg',
    isSaved: false,
  },
  {
    id: 'r_pollo_10',
    title: 'Arroz con Pollo a la Lata',
    description: 'Versión rápida del arroz con pollo usando pollo desmenuzado y caldo casero. Lista en 25 minutos.',
    prepTime: 25,
    energyLevel: 'low',
    utensils: ['olla mediana', 'cuchara de madera'],
    ingredientsNeeded: [
      { name: 'pollo cocido desmenuzado', required: true, inPantry: false },
      { name: 'arroz', required: true, inPantry: false },
      { name: 'caldo de pollo', required: true, inPantry: false },
      { name: 'cebolla', required: true, inPantry: false },
      { name: 'achiote', required: true, inPantry: false },
      { name: 'guisantes o arveja', required: false, inPantry: false },
      { name: 'sal y comino', required: true, inPantry: false },
    ],
    steps: [
      'Sofríe la cebolla picada con achiote en la olla hasta transparentar.',
      'Agrega el arroz lavado y revuelve para que tome el color del achiote.',
      'Vierte el caldo caliente (doble de volumen que el arroz) y sazona con sal y comino.',
      'Cuando rompa hervor, baja el fuego, tapa y cocina 15 minutos.',
      'Incorpora el pollo desmenuzado y los guisantes, mezcla suavemente.',
      'Deja reposar tapado 5 minutos y sirve.',
    ],
    imageUrl: '/images/recipes/r_pollo_10.jpg',
    isSaved: false,
  },

  // ─── PLÁTANO (10) ─────────────────────────────────────────────────────────
  {
    id: 'r_platano_01',
    title: 'Patacones con Hogao',
    description: 'Tostones de plátano verde fritos dos veces, aplastados y crujientes, servidos con hogao casero.',
    prepTime: 25,
    energyLevel: 'disconnect',
    utensils: ['sartén profunda', 'prensa o plato', 'papel absorbente'],
    ingredientsNeeded: [
      { name: 'plátano verde', required: true, inPantry: false },
      { name: 'aceite para freír', required: true, inPantry: false },
      { name: 'tomate chonto', required: true, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'sal', required: true, inPantry: false },
    ],
    steps: [
      'Pela el plátano verde y córtalo en rodajas de 3 cm.',
      'Fríe en aceite caliente 3 minutos por lado hasta ablandar. Retira y escurre.',
      'Aplasta cada rodaja con un plato o prensa hasta la mitad de su grosor.',
      'Regresa al aceite y fríe 2–3 minutos más hasta que estén dorados y crujientes.',
      'Para el hogao: sofríe cebolla, ajo y tomate picados hasta reducir. Sazona.',
      'Sirve los patacones con sal, hogao por encima y aguacate al lado.',
    ],
    imageUrl: '/images/recipes/r_platano_01.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_02',
    title: 'Tajadas de Plátano Maduro',
    description: 'Rodajas de plátano maduro fritas hasta caramelizar. El acompañante dulce infaltable en la mesa colombiana.',
    prepTime: 10,
    energyLevel: 'low',
    utensils: ['sartén', 'espátula', 'papel absorbente'],
    ingredientsNeeded: [
      { name: 'plátano maduro', required: true, inPantry: false },
      { name: 'aceite vegetal', required: true, inPantry: false },
      { name: 'sal (opcional)', required: false, inPantry: false },
    ],
    steps: [
      'Pela el plátano maduro y córtalo en rodajas diagonales de 1 cm.',
      'Calienta el aceite en la sartén a fuego medio.',
      'Fríe las tajadas 2–3 minutos por lado hasta que estén doradas y caramelizadas.',
      'Escurre en papel absorbente y sirve de inmediato como acompañante.',
    ],
    imageUrl: '/images/recipes/r_platano_02.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_03',
    title: 'Cayeye Costeño',
    description: 'Puré rústico de plátano verde hervido con suero costeño y queso, típico del desayuno Caribe colombiano.',
    prepTime: 20,
    energyLevel: 'low',
    utensils: ['olla', 'tenedor o pisapapas', 'tazón'],
    ingredientsNeeded: [
      { name: 'plátano verde', required: true, inPantry: false },
      { name: 'suero costeño', required: true, inPantry: false },
      { name: 'queso costeño rallado', required: true, inPantry: false },
      { name: 'mantequilla', required: false, inPantry: false },
      { name: 'sal', required: true, inPantry: false },
    ],
    steps: [
      'Pela el plátano verde, córtalo en trozos y hiérvelo en agua con sal 15 minutos.',
      'Escurre el plátano y aplásta con un tenedor mientras está caliente.',
      'Agrega el suero costeño y la mantequilla. Mezcla hasta obtener un puré.',
      'Sirve caliente con queso costeño rallado por encima.',
    ],
    imageUrl: '/images/recipes/r_platano_03.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_04',
    title: 'Plátano Maduro al Horno con Queso',
    description: 'Plátanos maduros horneados hasta suavizar, rellenos de queso blanco derretido. Postre o merienda tradicional.',
    prepTime: 25,
    energyLevel: 'disconnect',
    utensils: ['horno', 'bandeja para horno', 'cuchillo'],
    ingredientsNeeded: [
      { name: 'plátano maduro', required: true, inPantry: false },
      { name: 'queso blanco o mozzarella', required: true, inPantry: false },
      { name: 'mantequilla', required: false, inPantry: false },
      { name: 'canela (opcional)', required: false, inPantry: false },
    ],
    steps: [
      'Precalienta el horno a 180 °C.',
      'Haz un corte longitudinal a cada plátano sin pelarlo del todo.',
      'Rellena el corte con queso en rodajas y un trozo de mantequilla.',
      'Coloca en la bandeja y hornea 20 minutos hasta que el plátano esté blando.',
      'Sirve caliente; puedes espolvorear canela al gusto.',
    ],
    imageUrl: '/images/recipes/r_platano_04.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_05',
    title: 'Sancocho con Plátano Verde',
    description: 'Sopa contundente con plátano verde, yuca, papa y pollo. El sancocho trifásico que une familias colombianas.',
    prepTime: 45,
    energyLevel: 'disconnect',
    utensils: ['olla grande', 'cuchillo', 'tabla de cortar'],
    ingredientsNeeded: [
      { name: 'plátano verde', required: true, inPantry: false },
      { name: 'pollo en presas', required: true, inPantry: false },
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'yuca', required: false, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'cilantro y ajo', required: true, inPantry: false },
      { name: 'sal y comino', required: true, inPantry: false },
    ],
    steps: [
      'Hierve el pollo con agua, cebolla, ajo, sal y comino en la olla grande por 20 minutos.',
      'Pela y trocea el plátano verde, la yuca y la papa.',
      'Agrega el plátano y la yuca al caldo. Cocina 10 minutos.',
      'Incorpora la papa y cocina 15 minutos más hasta que todo esté blando.',
      'Ajusta la sal, agrega cilantro y sirve con arroz blanco y aguacate.',
    ],
    imageUrl: '/images/recipes/r_platano_05.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_06',
    title: 'Tostadas de Plátano con Hogao',
    description: 'Rodajas de plátano verde tostadas en el horno, cubiertas con hogao y queso. Snack crujiente y sabroso.',
    prepTime: 20,
    energyLevel: 'low',
    utensils: ['horno', 'bandeja', 'cuchillo', 'sartén'],
    ingredientsNeeded: [
      { name: 'plátano verde', required: true, inPantry: false },
      { name: 'tomate', required: true, inPantry: false },
      { name: 'cebolla', required: true, inPantry: false },
      { name: 'queso blanco', required: true, inPantry: false },
      { name: 'aceite de oliva', required: true, inPantry: false },
      { name: 'sal y ajo', required: true, inPantry: false },
    ],
    steps: [
      'Precalienta el horno a 200 °C.',
      'Pela el plátano, córtalo en rodajas finas, unta con aceite y coloca en la bandeja.',
      'Hornea 12–15 minutos hasta que estén crujientes.',
      'Prepara el hogao sofriendo cebolla, ajo y tomate picados.',
      'Saca las tostadas, cúbrelas con hogao y queso rallado.',
      'Regresa al horno 2 minutos para derretir el queso.',
    ],
    imageUrl: '/images/recipes/r_platano_06.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_07',
    title: 'Arroz con Coco y Plátano',
    description: 'Arroz costeño en leche de coco con tajadas de plátano maduro. Combinación dulce-salada del Caribe colombiano.',
    prepTime: 30,
    energyLevel: 'balanced',
    utensils: ['olla', 'sartén', 'cuchara de madera'],
    ingredientsNeeded: [
      { name: 'arroz', required: true, inPantry: false },
      { name: 'leche de coco', required: true, inPantry: false },
      { name: 'plátano maduro', required: true, inPantry: false },
      { name: 'aceite vegetal', required: true, inPantry: false },
      { name: 'sal y azúcar', required: true, inPantry: false },
    ],
    steps: [
      'Cocina el arroz en leche de coco mezclada con agua (1:2) con sal y una pizca de azúcar.',
      'Cuando rompa hervor, baja el fuego y tapa. Cocina 15 minutos.',
      'Corta el plátano maduro en tajadas diagonales.',
      'Fríe las tajadas en aceite 2–3 minutos por lado hasta caramelizar.',
      'Sirve el arroz con las tajadas encima y pescado frito si deseas.',
    ],
    imageUrl: '/images/recipes/r_platano_07.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_08',
    title: 'Plátano Asado con Mantequilla',
    description: 'Plátano maduro asado directamente en la llama o plancha, con mantequilla y sal. Desayuno antioqueño clásico.',
    prepTime: 15,
    energyLevel: 'low',
    utensils: ['plancha o sartén', 'cuchillo'],
    ingredientsNeeded: [
      { name: 'plátano maduro', required: true, inPantry: false },
      { name: 'mantequilla', required: true, inPantry: false },
      { name: 'sal', required: false, inPantry: false },
      { name: 'queso blanco (opcional)', required: false, inPantry: false },
    ],
    steps: [
      'Deja el plátano con cáscara y ponlo en la plancha o sartén a fuego medio.',
      'Asa 5–6 minutos por lado hasta que la cáscara esté negra y el plátano blando.',
      'Retira, haz un corte y ábrelo.',
      'Coloca una cucharada de mantequilla dentro y sirve con queso al lado.',
    ],
    imageUrl: '/images/recipes/r_platano_08.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_09',
    title: 'Bollo de Plátano Costeño',
    description: 'Masa de plátano verde rallado cocida en hoja de plátano. Desayuno tradicional del Caribe colombiano.',
    prepTime: 40,
    energyLevel: 'balanced',
    utensils: ['rallador', 'olla grande', 'hoja de plátano o papel aluminio'],
    ingredientsNeeded: [
      { name: 'plátano verde', required: true, inPantry: false },
      { name: 'sal', required: true, inPantry: false },
      { name: 'hoja de plátano', required: false, inPantry: false },
      { name: 'mantequilla', required: false, inPantry: false },
    ],
    steps: [
      'Pela y ralla finamente el plátano verde crudo.',
      'Sazona con sal y mezcla bien la masa.',
      'Envuelve porciones de masa en hojas de plátano o papel aluminio formando cilindros.',
      'Sella bien los extremos.',
      'Cocina en agua hirviendo 30–35 minutos.',
      'Retira, deja enfriar ligeramente y sirve con mantequilla y queso.',
    ],
    imageUrl: '/images/recipes/r_platano_09.jpg',
    isSaved: false,
  },
  {
    id: 'r_platano_10',
    title: 'Piononos de Plátano Maduro',
    description: 'Tajadas de plátano maduro rellenas de carne molida y queso, enrolladas y doradas en sartén.',
    prepTime: 35,
    energyLevel: 'balanced',
    utensils: ['sartén', 'mondadientes', 'cuchillo', 'espátula'],
    ingredientsNeeded: [
      { name: 'plátano maduro', required: true, inPantry: false },
      { name: 'carne molida', required: true, inPantry: false },
      { name: 'queso blanco', required: true, inPantry: false },
      { name: 'tomate y cebolla', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
      { name: 'sal y especias', required: true, inPantry: false },
    ],
    steps: [
      'Fríe las tajadas de plátano maduro hasta ablandar (no dorar). Reserva.',
      'Sofríe cebolla, ajo y tomate. Agrega la carne molida y cocina 8 minutos. Sazona.',
      'Coloca una tajada de plátano, agrega relleno de carne y queso, enrolla y sujeta con mondadiente.',
      'Dora los piononos en sartén con poco aceite por todos lados.',
      'Sirve caliente como entrada o plato principal.',
    ],
    imageUrl: '/images/recipes/r_platano_10.jpg',
    isSaved: false,
  },

  // ─── PAPA (10) ────────────────────────────────────────────────────────────
  {
    id: 'r_papa_01',
    title: 'Papa Criolla con Hogao',
    description: 'Papas criollas pequeñas cocinadas con su piel y bañadas en hogao. Simple, económico y delicioso.',
    prepTime: 20,
    energyLevel: 'low',
    utensils: ['olla', 'sartén', 'cuchara'],
    ingredientsNeeded: [
      { name: 'papa criolla', required: true, inPantry: false },
      { name: 'tomate chonto', required: true, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
      { name: 'sal y comino', required: true, inPantry: false },
    ],
    steps: [
      'Lava las papas criollas y hiérvelas con cáscara en agua con sal 15 minutos.',
      'Sofríe la cebolla y el ajo picados en aceite hasta transparentar.',
      'Agrega el tomate picado y el comino. Cocina 8 minutos para hacer el hogao.',
      'Escurre las papas y sírvelas enteras bañadas en el hogao caliente.',
    ],
    imageUrl: '/images/recipes/r_papa_01.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_02',
    title: 'Papas Fritas Crujientes',
    description: 'Papas pastusas cortadas en bastones y fritas dos veces para máxima crocancia. Acompañante infaltable.',
    prepTime: 30,
    energyLevel: 'disconnect',
    utensils: ['olla profunda', 'cuchillo', 'tabla de cortar', 'papel absorbente'],
    ingredientsNeeded: [
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'aceite para freír', required: true, inPantry: false },
      { name: 'sal', required: true, inPantry: false },
    ],
    steps: [
      'Pela las papas y córtalas en bastones uniformes de 1 cm.',
      'Remoja en agua fría 15 minutos para eliminar almidón. Seca muy bien.',
      'Primera fritura: fríe a 150 °C por 5 minutos hasta ablandar. Escurre.',
      'Segunda fritura: sube el aceite a 190 °C y fríe 2–3 minutos hasta dorar.',
      'Escurre en papel absorbente, sala inmediatamente y sirve.',
    ],
    imageUrl: '/images/recipes/r_papa_02.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_03',
    title: 'Ajiaco Bogotano',
    description: 'La sopa más emblemática de Bogotá: tres tipos de papa, pollo, mazorca y guasca. Sabor del altiplano.',
    prepTime: 45,
    energyLevel: 'disconnect',
    utensils: ['olla grande', 'cuchillo', 'tabla de cortar'],
    ingredientsNeeded: [
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'papa sabanera', required: true, inPantry: false },
      { name: 'papa criolla', required: true, inPantry: false },
      { name: 'pollo en presas', required: true, inPantry: false },
      { name: 'mazorca', required: true, inPantry: false },
      { name: 'guasca seca', required: true, inPantry: false },
      { name: 'cebolla larga y cilantro', required: true, inPantry: false },
    ],
    steps: [
      'Hierve el pollo con cebolla, ajo y sal por 20 minutos. Retira y desmecha.',
      'Al caldo agrega la papa pastusa y la sabanera en cubos. Cocina 15 minutos.',
      'Incorpora la papa criolla entera y la mazorca en rodajas. Agrega la guasca.',
      'Cocina 10 minutos más; la papa criolla se deshace espesando el caldo.',
      'Agrega el pollo desmechado, ajusta la sal y sirve con crema de leche, alcaparras y aguacate.',
    ],
    imageUrl: '/images/recipes/r_papa_03.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_04',
    title: 'Puré de Papa con Mantequilla',
    description: 'Puré cremoso de papa pastusa con mantequilla y leche. Guarnición reconfortante para cualquier proteína.',
    prepTime: 25,
    energyLevel: 'low',
    utensils: ['olla', 'pisapapas', 'tazón'],
    ingredientsNeeded: [
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'mantequilla', required: true, inPantry: false },
      { name: 'leche caliente', required: true, inPantry: false },
      { name: 'sal y nuez moscada', required: true, inPantry: false },
    ],
    steps: [
      'Pela las papas y córtalas en cubos. Hierve con agua y sal hasta que estén muy blandas.',
      'Escurre bien y aplasta con el pisapapas mientras están calientes.',
      'Agrega la mantequilla y mezcla hasta incorporar.',
      'Añade la leche caliente poco a poco hasta lograr consistencia cremosa.',
      'Sazona con sal y nuez moscada. Sirve inmediatamente.',
    ],
    imageUrl: '/images/recipes/r_papa_04.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_05',
    title: 'Papas Rellenas Colombianas',
    description: 'Bolas de puré de papa rellenas de carne guisada, empanizadas y fritas. Snack o entrada reconocida.',
    prepTime: 45,
    energyLevel: 'balanced',
    utensils: ['olla', 'sartén', 'tazón', 'papel absorbente'],
    ingredientsNeeded: [
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'carne molida', required: true, inPantry: false },
      { name: 'tomate y cebolla', required: true, inPantry: false },
      { name: 'huevo', required: true, inPantry: false },
      { name: 'pan rallado', required: true, inPantry: false },
      { name: 'aceite para freír', required: true, inPantry: false },
      { name: 'sal y especias', required: true, inPantry: false },
    ],
    steps: [
      'Cocina y aplasta las papas para hacer puré. Sazona y deja enfriar.',
      'Sofríe cebolla, tomate y carne molida. Sazona y deja enfriar el relleno.',
      'Toma porciones de puré, aplana, coloca relleno en el centro y forma bolas.',
      'Pasa cada bola por huevo batido y luego por pan rallado.',
      'Fríe en aceite caliente hasta dorar por todos lados.',
      'Escurre y sirve con ají.',
    ],
    imageUrl: '/images/recipes/r_papa_05.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_06',
    title: 'Papas al Horno con Crema',
    description: 'Papas horneadas enteras con cáscara, abiertas y rellenas de crema, queso y cebollín. Fácil y satisfactorio.',
    prepTime: 45,
    energyLevel: 'disconnect',
    utensils: ['horno', 'bandeja', 'cuchillo'],
    ingredientsNeeded: [
      { name: 'papa grande pastusa', required: true, inPantry: false },
      { name: 'crema de leche', required: true, inPantry: false },
      { name: 'queso cheddar o blanco', required: true, inPantry: false },
      { name: 'cebollín', required: false, inPantry: false },
      { name: 'mantequilla', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Precalienta el horno a 200 °C.',
      'Lava bien las papas, pícalas con tenedor por todos lados y unta con aceite y sal.',
      'Hornea directamente en la rejilla 40–45 minutos hasta que estén tiernas.',
      'Haz un corte en cruz, presiona los extremos para abrir.',
      'Rellena con mantequilla, crema, queso rallado y cebollín.',
      'Regresa al horno 5 minutos para derretir el queso.',
    ],
    imageUrl: '/images/recipes/r_papa_06.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_07',
    title: 'Papas Guisadas con Chorizo',
    description: 'Papa criolla guisada con chorizo colombiano, cebolla y ají. Plato de olla reconfortante y económico.',
    prepTime: 30,
    energyLevel: 'balanced',
    utensils: ['olla', 'sartén', 'cuchara de madera'],
    ingredientsNeeded: [
      { name: 'papa criolla', required: true, inPantry: false },
      { name: 'chorizo colombiano', required: true, inPantry: false },
      { name: 'tomate', required: true, inPantry: false },
      { name: 'cebolla', required: true, inPantry: false },
      { name: 'ají', required: false, inPantry: false },
      { name: 'aceite y sal', required: true, inPantry: false },
      { name: 'comino y laurel', required: true, inPantry: false },
    ],
    steps: [
      'Dora el chorizo en rodajas en la olla. Retira y reserva la grasa.',
      'Sofríe cebolla, tomate y ají en la misma olla con el aceite del chorizo.',
      'Agrega las papas criollas lavadas (con cáscara) y el chorizo.',
      'Cubre con agua o caldo, agrega laurel y comino. Tapa.',
      'Cocina a fuego medio 20 minutos hasta que las papas estén tiernas.',
      'Ajusta la sal y sirve con arroz blanco.',
    ],
    imageUrl: '/images/recipes/r_papa_07.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_08',
    title: 'Tortilla de Papa Campesina',
    description: 'Tortilla española colombiana con papa, cebolla y huevo. Desayuno o cena rápida y nutritiva.',
    prepTime: 25,
    energyLevel: 'low',
    utensils: ['sartén antiadherente', 'tazón', 'espátula'],
    ingredientsNeeded: [
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'huevos', required: true, inPantry: false },
      { name: 'cebolla cabezona', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Pela y corta las papas en láminas finas. Sofríe con cebolla en aceite 10 minutos.',
      'Bate los huevos con sal y pimienta en un tazón.',
      'Mezcla las papas y cebolla pochadas con los huevos batidos.',
      'Vierte la mezcla en la sartén caliente con un poco de aceite.',
      'Cocina a fuego medio-bajo 5 minutos, voltea con un plato y cocina 3 minutos más.',
      'Sirve en porciones con pan o arepa.',
    ],
    imageUrl: '/images/recipes/r_papa_08.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_09',
    title: 'Papas Chorreadas Bogotanas',
    description: 'Papa pastusa cocida bañada en salsa de hogao con crema de leche. Un clásico indiscutible de la cocina bogotana.',
    prepTime: 25,
    energyLevel: 'low',
    utensils: ['olla', 'sartén', 'cuchara'],
    ingredientsNeeded: [
      { name: 'papa pastusa mediana', required: true, inPantry: false },
      { name: 'tomate chonto', required: true, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'crema de leche', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
      { name: 'sal, comino y cilantro', required: true, inPantry: false },
    ],
    steps: [
      'Hierve las papas con cáscara en agua con sal hasta que estén blandas (20 min).',
      'Sofríe la cebolla larga picada en aceite hasta transparentar.',
      'Agrega el tomate picado y el comino. Cocina 8 minutos (hogao).',
      'Incorpora la crema de leche al hogao y revuelve. Cocina 2 minutos.',
      'Pela las papas o sírvelas con cáscara. Baña con la salsa chorreada.',
      'Esparce cilantro picado y sirve de inmediato.',
    ],
    imageUrl: '/images/recipes/r_papa_09.jpg',
    isSaved: false,
  },
  {
    id: 'r_papa_10',
    title: 'Sancocho de Papa con Costilla',
    description: 'Sancocho espeso de papa pastusa con costilla de res, perfecto para el almuerzo familiar del domingo.',
    prepTime: 45,
    energyLevel: 'disconnect',
    utensils: ['olla grande', 'cuchillo', 'tabla'],
    ingredientsNeeded: [
      { name: 'papa pastusa', required: true, inPantry: false },
      { name: 'costilla de res', required: true, inPantry: false },
      { name: 'cebolla larga', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'cilantro', required: true, inPantry: false },
      { name: 'plátano verde', required: false, inPantry: false },
      { name: 'sal y comino', required: true, inPantry: false },
    ],
    steps: [
      'Hierve la costilla con agua, cebolla, ajo, sal y comino por 25 minutos a fuego alto.',
      'Pela las papas, córtalas en cubos grandes y agrégalas al caldo.',
      'Incorpora el plátano troceado si lo usas. Cocina 15 minutos más.',
      'Cuando las papas estén blandas, aplasta algunas con cuchara para espesar.',
      'Ajusta la sazón, agrega cilantro y sirve en tazones grandes.',
    ],
    imageUrl: '/images/recipes/r_papa_10.jpg',
    isSaved: false,
  },

  // ─── AGUACATE (10) ────────────────────────────────────────────────────────
  {
    id: 'r_aguacate_01',
    title: 'Guacamole Colombiano',
    description: 'Guacamole criollo con aguacate Hass, limón, cilantro y ají. Dip fresco para compartir con patacones.',
    prepTime: 10,
    energyLevel: 'low',
    utensils: ['tazón', 'tenedor', 'cuchillo'],
    ingredientsNeeded: [
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'cilantro fresco', required: true, inPantry: false },
      { name: 'cebolla morada', required: true, inPantry: false },
      { name: 'ají o jalapeño', required: false, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Abre el aguacate, retira la semilla y saca la pulpa al tazón.',
      'Aplasta con un tenedor dejando algo de textura rústica.',
      'Agrega el jugo de limón, la cebolla morada finamente picada y el cilantro.',
      'Mezcla el ají si deseas picante. Sazona con sal y pimienta.',
      'Sirve de inmediato con patacones, tostadas o chips.',
    ],
    imageUrl: '/images/recipes/r_aguacate_01.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_02',
    title: 'Ensalada Verde con Aguacate',
    description: 'Ensalada de lechuga, tomate y aguacate con vinagreta de limón y aceite de oliva. Fresca y ligera.',
    prepTime: 10,
    energyLevel: 'low',
    utensils: ['tazón grande', 'cuchillo', 'tabla de cortar'],
    ingredientsNeeded: [
      { name: 'lechuga', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'tomate', required: true, inPantry: false },
      { name: 'pepino', required: false, inPantry: false },
      { name: 'aceite de oliva', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Lava y desmenuza la lechuga en el tazón.',
      'Pica el tomate, pepino y aguacate en cubos medianos.',
      'Prepara la vinagreta mezclando aceite, limón, sal y pimienta.',
      'Combina todos los vegetales en el tazón y baña con la vinagreta.',
      'Sirve de inmediato para evitar que el aguacate se oxide.',
    ],
    imageUrl: '/images/recipes/r_aguacate_02.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_03',
    title: 'Arepa con Aguacate y Queso',
    description: 'Arepa blanca caliente untada con aguacate y queso blanco rallado. Desayuno colombiano irresistible.',
    prepTime: 15,
    energyLevel: 'low',
    utensils: ['budare o plancha', 'cuchillo', 'tazón'],
    ingredientsNeeded: [
      { name: 'arepa blanca', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'queso blanco', required: true, inPantry: false },
      { name: 'sal', required: true, inPantry: false },
      { name: 'mantequilla (opcional)', required: false, inPantry: false },
    ],
    steps: [
      'Calienta la arepa en el budare o plancha 5 minutos por lado.',
      'Abre el aguacate, retira la semilla y aplasta la pulpa con tenedor.',
      'Sazona el aguacate con sal.',
      'Parte la arepa caliente, unta con mantequilla si deseas.',
      'Agrega el aguacate aplastado y el queso blanco rallado encima.',
    ],
    imageUrl: '/images/recipes/r_aguacate_03.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_04',
    title: 'Pollo con Crema de Aguacate',
    description: 'Pechuga de pollo a la plancha sobre salsa cremosa de aguacate con limón y cilantro.',
    prepTime: 35,
    energyLevel: 'disconnect',
    utensils: ['sartén', 'licuadora o tazón', 'cuchillo'],
    ingredientsNeeded: [
      { name: 'pechuga de pollo', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'cilantro', required: true, inPantry: false },
      { name: 'ajo', required: true, inPantry: false },
      { name: 'aceite', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Marina la pechuga en ajo, limón, aceite, sal y pimienta 10 minutos.',
      'Cocina a la plancha 5 minutos por lado hasta dorar. Deja reposar.',
      'Procesa el aguacate con limón, cilantro, ajo y sal hasta obtener crema.',
      'Rebana la pechuga y sirve sobre la crema de aguacate.',
      'Decora con cilantro fresco y rodajas de limón.',
    ],
    imageUrl: '/images/recipes/r_aguacate_04.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_05',
    title: 'Arroz con Aguacate y Limón',
    description: 'Arroz blanco suelto mezclado con aguacate en cubos, limón y cilantro. Guarnición fresca y diferente.',
    prepTime: 20,
    energyLevel: 'low',
    utensils: ['olla', 'tazón', 'cuchara'],
    ingredientsNeeded: [
      { name: 'arroz', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'cilantro', required: true, inPantry: false },
      { name: 'aceite de oliva', required: true, inPantry: false },
      { name: 'sal', required: true, inPantry: false },
    ],
    steps: [
      'Cocina el arroz blanco según las instrucciones. Deja enfriar ligeramente.',
      'Pica el aguacate en cubos medianos y báñalos con limón para evitar oxidación.',
      'Mezcla el arroz con aceite de oliva, sal y cilantro picado.',
      'Incorpora los cubos de aguacate suavemente.',
      'Sirve a temperatura ambiente o ligeramente frío.',
    ],
    imageUrl: '/images/recipes/r_aguacate_05.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_06',
    title: 'Crema Fría de Aguacate',
    description: 'Sopa fría de aguacate con pepino y limón. Refrescante, saludable y lista en 5 minutos.',
    prepTime: 10,
    energyLevel: 'low',
    utensils: ['licuadora', 'tazones'],
    ingredientsNeeded: [
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'pepino', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'agua fría o caldo vegetal', required: true, inPantry: false },
      { name: 'ajo', required: false, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
      { name: 'cilantro', required: false, inPantry: false },
    ],
    steps: [
      'Pela y trocea el aguacate y el pepino.',
      'Coloca en la licuadora con el agua fría, limón, ajo y sal.',
      'Licúa hasta obtener consistencia cremosa y homogénea.',
      'Ajusta la sal y agrega más agua si quieres consistencia más líquida.',
      'Refrigera 10 minutos y sirve con cilantro y un chorrito de aceite de oliva.',
    ],
    imageUrl: '/images/recipes/r_aguacate_06.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_07',
    title: 'Wrap de Aguacate y Pollo',
    description: 'Tortilla de maíz enrollada con pollo desmenuzado, aguacate, lechuga y tomate. Almuerzo rápido y completo.',
    prepTime: 15,
    energyLevel: 'low',
    utensils: ['sartén', 'tabla de cortar', 'cuchillo'],
    ingredientsNeeded: [
      { name: 'tortilla de maíz o trigo', required: true, inPantry: false },
      { name: 'pollo cocido desmenuzado', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'lechuga', required: true, inPantry: false },
      { name: 'tomate', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
    ],
    steps: [
      'Calienta las tortillas en sartén seca 1 minuto por lado.',
      'Aplasta el aguacate con limón, sal y pimienta.',
      'Unta el aguacate sobre la tortilla como base.',
      'Coloca la lechuga, el pollo desmenuzado y el tomate picado.',
      'Enrolla firmemente y corta en diagonal.',
    ],
    imageUrl: '/images/recipes/r_aguacate_07.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_08',
    title: 'Pico de Gallo con Aguacate',
    description: 'Mezcla fresca de tomate, cebolla, ají, cilantro y aguacate. Salsa colombiana para acompañar carnes y arepas.',
    prepTime: 10,
    energyLevel: 'low',
    utensils: ['tazón', 'cuchillo', 'tabla de cortar'],
    ingredientsNeeded: [
      { name: 'tomate maduro', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'cebolla morada', required: true, inPantry: false },
      { name: 'cilantro fresco', required: true, inPantry: false },
      { name: 'ají o chile verde', required: false, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'sal', required: true, inPantry: false },
    ],
    steps: [
      'Pica el tomate, la cebolla morada y el ají en cubos pequeños.',
      'Pica el aguacate en cubos y báñalos con limón de inmediato.',
      'Mezcla todo en el tazón con el cilantro picado fino.',
      'Sazona con sal y más limón al gusto.',
      'Deja reposar 5 minutos para que los sabores se integren.',
    ],
    imageUrl: '/images/recipes/r_aguacate_08.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_09',
    title: 'Huevos Revueltos con Aguacate',
    description: 'Huevos cremosos revueltos a fuego bajo, servidos sobre tostadas con aguacate. Desayuno poderoso y fácil.',
    prepTime: 10,
    energyLevel: 'low',
    utensils: ['sartén antiadherente', 'tazón', 'espátula'],
    ingredientsNeeded: [
      { name: 'huevos', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'mantequilla', required: true, inPantry: false },
      { name: 'pan integral o arepa', required: true, inPantry: false },
      { name: 'sal y pimienta', required: true, inPantry: false },
      { name: 'cilantro o cebollín', required: false, inPantry: false },
    ],
    steps: [
      'Bate los huevos con sal y pimienta en el tazón.',
      'Derrite la mantequilla en sartén a fuego bajo.',
      'Agrega los huevos y revuelve constantemente con la espátula para huevos cremosos.',
      'Retira del fuego cuando estén casi cuajados (terminan de cocinarse con el calor residual).',
      'Sirve sobre pan tostado o arepa con aguacate en rodajas y cilantro.',
    ],
    imageUrl: '/images/recipes/r_aguacate_09.jpg',
    isSaved: false,
  },
  {
    id: 'r_aguacate_10',
    title: 'Ceviche de Camarón con Aguacate',
    description: 'Ceviche colombiano de camarones cocidos con limón, cebolla morada, cilantro y aguacate fresco.',
    prepTime: 35,
    energyLevel: 'balanced',
    utensils: ['tazón grande', 'cuchillo', 'tabla de cortar'],
    ingredientsNeeded: [
      { name: 'camarones cocidos', required: true, inPantry: false },
      { name: 'aguacate maduro', required: true, inPantry: false },
      { name: 'jugo de limón', required: true, inPantry: false },
      { name: 'cebolla morada', required: true, inPantry: false },
      { name: 'cilantro fresco', required: true, inPantry: false },
      { name: 'tomate', required: true, inPantry: false },
      { name: 'sal, pimienta y ají', required: true, inPantry: false },
    ],
    steps: [
      'Corta los camarones cocidos en trozos medianos.',
      'Marina en jugo de limón con sal, pimienta y ají 10 minutos.',
      'Pica la cebolla morada, el tomate y el cilantro finamente.',
      'Mezcla todo con los camarones marinados.',
      'Incorpora el aguacate en cubos justo antes de servir para que no se rompa.',
      'Sirve frío con patacones o tostadas.',
    ],
    imageUrl: '/images/recipes/r_aguacate_10.jpg',
    isSaved: false,
  },
];
